---
- name: Dynamically retrieve region and ACM Private CA ARN and generate CSR
  hosts: localhost
  become: true
  tasks:

    - name: Generate an OpenSSL private key with a different size (2048 bits)
      community.crypto.openssl_privatekey:
        path: /etc/ssl/private/instance_csr.pem
        size: 2048



    - name: Generate an OpenSSL Certificate Signing Request (CSR)
      community.crypto.openssl_csr:
        path: /etc/ssl/private/instance_csr.csr
        privatekey_path: /etc/ssl/private/instance_csr.pem
        country_name: ${country}
        organization_name: ${organization}
        common_name: ${common_name}
        locality_name: ${locality}
        state_or_province_name: ${state}
        organizational_unit_name: ${organizational_unit}
        subject_alt_name: "DNS:{{ ansible_hostname }}"

    - name: Request a certificate from ACM Private CA
      ansible.builtin.shell: |
        aws acm-pca issue-certificate \
          --region ${region} \
          --certificate-authority-arn ${pca_arn} \
          --csr file:///etc/ssl/private/instance_csr.csr \
          --signing-algorithm "SHA256WITHRSA" \
          --validity Value=365,Type="DAYS" \
          --idempotency-token $(uuidgen) \
          --query 'CertificateArn' \
          --output text
      register: cert_arn

    - name: Wait for certificate to be issued
      ansible.builtin.pause:
        seconds: 30  # Adjust as needed to ensure the certificate is issued

    - name: Retrieve the certificate
      ansible.builtin.shell: |
        aws acm-pca get-certificate \
          --region ${region} \
          --certificate-authority-arn ${pca_arn} \
          --certificate-arn {{ cert_arn.stdout }} \
          --query '{Certificate:Certificate,CertificateChain:CertificateChain}' \
          --output json
      register: certificate_output

    - name: Write certificate to file
      ansible.builtin.copy:
        content: "{{ certificate_output.stdout | from_json | json_query('Certificate') }}"
        dest: /etc/ssl/certs/instance_cert.crt

    - name: Write certificate chain to file
      ansible.builtin.copy:
        content: "{{ certificate_output.stdout | from_json | json_query('CertificateChain') }}"
        dest: /etc/ssl/certs/ca_chain.crt
